### ISSUE TITLE
Class declaration with inline initialization.

### ISSUE THREAD

**Issue by Farious** [miguelfmlopes91/SDL-Bardo-Engine#15]
https://github.com/miguelfmlopes91/SDL-Bardo-Engine/blob/70fa718181a300a5ade4d5d7842862b68b14a8d2/SDL%20Bardo%20Engine%20visual%20studio/SDL%20Bardo%20Engine%20visual%20studio/Bitmap.h#L24

Consider adding an explicit default value to these integers. (This same approach could be applied into other classes)

**Comment by miguelfmlopes91** [comment]
fixed!
